# Generated by Django 4.2.7 on 2023-11-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy_finch_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='toys',
        ),
        migrations.AddField(
            model_name='toy',
            name='finch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.finch'),
        ),
    ]
